export { default as aperitifs } from './aperitifs.svg'
export { default as biscuit } from './biscuit.svg'
export { default as cheatmeal } from './cheatmeal.svg'
export { default as gateau } from './gateau.svg'
export { default as healthy } from './healthy.svg'
export { default as petitdej } from './petitdej.svg'
export { default as recette_sucree } from './recette-sucree.svg'
export { default as recette_salee } from './recette-salee.svg'
